version: '3.8'

services:
  haraka:
    image: haraka/haraka    # 官方 Haraka Docker 映像
    container_name: haraka_server
    ports:
      - "30:25"             # SMTP 服務端口
      - "587:587"           # 可選的 Submission 端口
    volumes:
      - ./data:/data        # 配置目錄掛載到主機
    environment:
      HARAKA_CONFIG: /data  # 指定 Haraka 的配置目錄
    restart: unless-stopped
